---

-

  # This playbook considers an Ubuntu 14.04 machine.
  hosts: deploy-hosts

  sudo: true

  tasks:
  - include: actions/create-groups.yml

  # Updates package list with the newest NodeJs repo.
  - shell: curl -sL https://deb.nodesource.com/setup_dev | bash -

  - apt: update_cache=yes

  - include: actions/install-dev-env.yml

  - shell: ln -s /lib/x86_64-linux-gnu/libtinfo.so.5.9 /lib/x86_64-linux-gnu/libtinfo.so

  # TODO: set up PATH in the environment as:
  # export PATH=$PATH:/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin

  - shell: /opt/cabal/1.22/bin/cabal update
    environment:
           PATH: "{{ ansible_env.PATH }}:/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin"
           LD_LIBRARY_PATH: "/lib/x86_64-linux-gnu"

  - shell: cabal install clash-ghc-5.8
    environment:
           PATH: "{{ ansible_env.PATH }}:/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin"
           LD_LIBRARY_PATH: "/lib/x86_64-linux-gnu"


  roles:
    - vim
    - utilities
    - nodejs
